spring:
  profiles:
    active: ${APP_PROFILE}
  application:
    name: avanade
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: geor8823
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            nan_contextual_creation: true
server:
  port: 8080